### ISSUE TITLE
Property too long to index "execution_argument" 

### ISSUE THREAD

**Issue by joksa97** [frikky/Shuffle#112]
**Describe the bug**
We have problem when TheHive webhook send case / alert in JASON format, it is too long for Shuffle to process and give this error. Is there any command or parameter to change to fix this issue?

**Expected behavior**
Shuffle can parse and send full JSON format from log.

**Screenshots**

![image](https://user-images.githubusercontent.com/18016433/90014629-b7d41480-dca7-11ea-9592-98bca840a478.png)

** Debug logs **
2020/08/12 12:11:32 Error adding workflow_execution: datastore: string property too long to index for a Property with Name "execution_argument"
2020/08/12 12:11:32 Error saving workflow execution for updates workflows: datastore: string property too long to index for a Property with Name "execution_argument"

```

**Comment by djordjezecevic** [comment]
Same here. Webhook from The hive has a JSON payload that can not fit to $exec.

**Comment by djordjezecevic** [comment]
After some investigation it is Google DB index limit. https://cloud.google.com/datastore/docs/concepts/limits
--
Maximum size of an indexed string property's UTF-8 encoding | 1,500 bytes
--

**Comment by frikky** [comment]
Hey guys, I'll fix this and rebuild it tomorrow! Been off on holiday for a few days :+1:

**Comment by frikky** [comment]
Should now be fixed. How to update: https://shuffler.io/docs/configuration#updating_shuffle

Please tell me if it works as expected. Thanks :100:

**Comment by joksa97** [comment]
Thank you. It is fixed for some cases, but there are still some types: for example when new QRadar alert is generated in TheHive, it says same error. Is there something to set this value to unlimited or something like this?

![image](https://user-images.githubusercontent.com/18016433/90245363-d1ee2e00-de32-11ea-9302-bedd9cbe0cc7.png)

**Comment by djordjezecevic** [comment]
Hello, 
I tried new versopn also. I test this by manualy filling Execution Argument in frontend. Before this update I was getting an error in browser and error in backend logs.
Now, workflow in frontend just hungs on start node, and backend error is same as @joksa97  described. I tried several sizes and 1.5 KB is still limit.

Best regards,
Djordje

**Comment by frikky** [comment]
Found the real issue. Thanks for the patience - a new version is built and uploaded :rocket:

**Comment by joksa97** [comment]
Are you sure you uploaded, because when i update Shuffle like you said.. And still get error, but also it said that it is already updated. I also see last modification is 3 days ago, not yesturday?

**Comment by frikky** [comment]
@joksa97 - You're right again. Will be great when I get a proper CI/CD pipeline for this to avoid these issues :+1: 

Uploaded and tested in docker!
